functional:
  - Пользователь должен иметь возможность поиска ментора по професии, инструментам, компании ментора, опыту или любой информации, указанной в профиле ментора
  - Пользователь должен иметь возможность фильтрации списка менторов по компании и профессии
  - Пользователь должен иметь возможность сортировки списка менторов по опыту и цене
  - У пользователя есть возможность сбросить все выбранные фильтры и сортировку
  - Пользователь должен иметь возможность поддержать проект через донат (Patreon, PayPal, Тинькофф)
  - В карточке ментора должны отображаться Имя, Фамилия, должность и место работы, опыт, стоимость занятия, количество менти.
  - На главной странице должно быть краткое описание принципа работы сервиса
  - FAQ на главной странице
  - Контакты для обратной связи с в подвале сайта
  - Ссылка на блог GetMentor в шапке сайта
  - Пользователь должен иметь возможность стать ментором
  - Пользователь должен иметь возможность просматривать полный профиль ментора в списке
  - Пользователь должен иметь возможность записаться к ментору из его профиля
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах (адаптивность)
implicit:
  - Протокол HTTPS
  - При подаче анкеты на менторство появляется сообщение об успешной отправке
  - Авторизация ментора происходит через облачный сервис airtable.com
  - При подаче заявки на запись к ментору появляется сообщение об успешной отправке
