functional:
  - Пользователь должен иметь возможность поиска ментора по професии, инструментам, компании ментора, опыту или любой информации, указанной в профиле ментора
  - Пользователь должен иметь возможность фильтрации списка менторов по компании и профессии
  - Пользователь должен иметь возможность сортировки списка менторов по опыту и цене
  - У пользователя есть возможность сбросить все выбранные фильтры и сортировку
  - Пользователь должен иметь возможность поддержать проект через донат (Patreon, PayPal, Тинькофф)
  - В карточке ментора должны отображаться Имя, Фамилия, должность и место работы, опыт, стоимость занятия, количество менти.
  - На главной странице должно быть краткое описание принципа работы сервиса
  - FAQ на главной странице
  - Контакты для обратной связи с в подвале сайта
  - Ссылка на блог GetMentor в шапке сайта
  - Пользователь должен иметь возможность стать ментором
  - Пользователь должен иметь возможность просматривать полный профиль ментора в списке
  - Пользователь должен иметь возможность записаться к ментору из его профиля
  - Форма записи к ментору и заявка на ментора содержит обязательные поля для заполнения
  - Пользователь имеет возможность получить копию своей заявки на ментора на электронную почту
  - Заявка на ментора должна содержать поля — Имя и фамилия, email, telegram, фотография, должность, место работы, о себе, уровень менти, опыт, специализация, навыки, стоимость, ссылка на календарь, соглашение с политикой конфиденциальности
  - Заявка на менти должна содержать поля — email, имя и фамилия, краткое описание вопросов, уровень знаний, telegram
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах (адаптивность)
implicit:
  - Протокол HTTPS
  - При подаче анкеты на менторство появляется сообщение об успешной отправке
  - Авторизация ментора происходит через облачный сервис airtable.com
  - При подаче заявки на запись к ментору появляется сообщение об успешной отправке
  - Все поля в формах "Стать ментором" и "Записаться к ментору" являются обязательными
  - При незаполнении обязательного поля в форме "Стать ментором" и "Записаться к ментору" появляется ошибка "This field is required. You have to enter something before submitting."
  - При некорректном заполнении обязательных полей (email, пароль и т.д) появляется сообщение, указывающее на места и причины ошибок
  - Валидация поля ввода "Адрес электронной почты" — должно иметь обязательный формат "@домен"
  - Валидация текстового поля ввода "Ваше имя и фамилия" — нельзя вводить цифры
  - Валидация поля "Ник в телеграм" — без "@" вначале
  - Поле "Опыт" содержит выпадающий список — 2-5 лет, 5-10 лет, 10+ 
  - Поле "Ваша специализация" содержит список тегов для выбора. Максимум 5
  - Поле "Стоимость консультации" содержит выпадающий список, включая "Бесплатно" и "По договоренности" 
  - Поле "Соглашение с политикой конфиденциальности" содержит обязательный чекбокс
  - Копия заявки на ментора приходит на электронный адрес, указанный в заявке в поле "Адрес электронной почты"
  - Поле ввода "Как вы оцениваете свой уровень?" в записи к ментору содержит выпадающий список с основными уровнями в IT
